# Generated by Django 2.0.2 on 2018-03-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='landing_page_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the text to be placed in the landing page home webpage.', max_length=200)),
            ],
        ),
    ]
