# Generated by Django 2.0.2 on 2018-03-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_landing_page_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing_page_home',
            name='name',
            field=models.TextField(help_text='Enter the text to be placed in the landing page home webpage.', max_length=1000),
        ),
    ]
