# Generated by Django 2.0.2 on 2018-03-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20180307_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing_page_header',
            name='id',
        ),
        migrations.RemoveField(
            model_name='landing_page_home',
            name='id',
        ),
        migrations.AlterField(
            model_name='landing_page_header',
            name='name',
            field=models.CharField(help_text='Enter the text to be placed in the header icon.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landing_page_home',
            name='name',
            field=models.TextField(help_text='Enter the text to be placed in the landing page home webpage.', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
