# Generated by Django 2.0.2 on 2018-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20180307_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='landing_page_content',
            fields=[
                ('name', models.TextField(help_text='Enter the text to be placed in the landing page content webpage.', max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
    ]
