# Generated by Django 2.0.1 on 2018-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_landing_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page_header',
            name='header_number',
            field=models.IntegerField(default=0),
        ),
    ]
