# Generated by Django 2.0.1 on 2018-03-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_landing_page_header_header_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page_home',
            name='header_number',
            field=models.IntegerField(default=0),
        ),
    ]
