# Generated by Django 2.0.1 on 2018-03-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_landing_page_home_header_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing_page_header',
            old_name='header_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='landing_page_home',
            old_name='header_number',
            new_name='number',
        ),
    ]
