# Generated by Django 2.0.1 on 2018-03-26 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_auto_20180326_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='landing_page_header',
        ),
    ]
