# Generated by Django 2.0.1 on 2018-03-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_delete_landing_page_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='landing_page_content',
        ),
        migrations.DeleteModel(
            name='landing_page_home',
        ),
    ]
